name: Appflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This will build an APK & Upload the artifact in Android.zip
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Build Android with Appflow
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.APPFLOW_TOKEN }}
          app-id: 32316914
          platform: Android
          build-type: debug
          environment: staging
          native-config: staging
          upload-artifact: Android
