name: Appflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Build Android with Appflow
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.APPFLOW_TOKEN }}
          app-id: 32316914
          platform: Android
          build-type: debug
          environment: staging
          native-config: staging
          upload-artifact: Android
          web-preview: yes

      - uses: actions/download-artifact@v2
        id: download
        with:
          name: 'Android'
          path: path/to/artifacts

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}

      - name: Upload to slack step
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          path: ${{steps.download.outputs.download-path}}
          channel: C02951193PH

      # - name: Send Message to Slack
      #   uses: archive/github-actions-slack@v2.0.1
      #   id: notify
      #   with:
      #     slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
      #     slack-channel: C02951193PH
      #     slack-text: Hello! Deployment happening in "${{ github.repository }}" \r\n \r\n *Description* \r\n ```${{github.event.pull_request.body}}```
      # - name: Result from "Send Message"
      #   run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
      # - name: get github events
      #   run: |
      #     echo "${{toJSON(github.event.pull_request)}}"

